### Get meal
GET http://localhost:8080/topjava/rest/profile/meals/100005

### Delete meal
DELETE http://localhost:8080/topjava/rest/profile/meals/100002

### Get all meals
GET http://localhost:8080/topjava/rest/profile/meals

### Create new meal
# curl -i -X POST http://localhost:8080/topjava/rest/profile/meals
#-d '{"dateTime":"2020-11-25T16:00:00", "description":"New Meal", "calories":1500}'
#-H 'Content-Type: application/json;charset=UTF-8'
POST http://localhost:8080/topjava/rest/profile/meals
Content-Type: application/json;charset=UTF-8

{
  "dateTime": "2020-11-25T17:00:00",
  "description": "New Meal",
  "calories": 1500
}

### Update meal
# curl -i -X PUT http://localhost:8080/topjava/rest/profile/meals/100004
#-d '{"id":100004, "dateTime":"2020-01-30T20:00:00", "description":"Update Meal", "calories":1500}'
#-H 'Content-Type: application/json;charset=UTF-8'
PUT http://localhost:8080/topjava/rest/profile/meals/100003
Content-Type: application/json;charset=UTF-8

{
  "id": 100003,
  "dateTime": "2020-01-30T13:00:00",
  "description": "Update Meal",
  "calories": 1500
}

### Meal filter for the period
GET http://localhost:8080/topjava/rest/profile/meals/filter?startDate=2020-01-31&startTime=06:00&endDate=2020-01-31&endTime=13:00

### Meal filter all
GET http://localhost:8080/topjava/rest/profile/meals/filter?startDate=&endTime=
